apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer  # Use ClusterIP if only internal access is needed
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000       # Flask app's container port
      targetPort: 5000 # Container listening on port 5000
